### Imports

In [1]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.graphics.factorplots import interaction_plot
import matplotlib.pyplot as plt

In [2]:
! pip install pyDOE2 #intalar pyDOE2 localmente

Requirement already satisfied: pyDOE2 in /opt/anaconda3/lib/python3.7/site-packages (1.3.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.7/site-packages (from pyDOE2) (1.19.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.7/site-packages (from pyDOE2) (1.6.2)

In [3]:
import pyDOE2

In [4]:
Cuadrado = pyDOE2.fracfact('A B C ABC')
Cuadrado = pd.DataFrame(Cuadrado, columns=['A', 'B', 'C', 'D'])
Cuadrado

     A    B    C    D
0 -1.0 -1.0 -1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0 -1.0  1.0  1.0
5  1.0 -1.0  1.0 -1.0
6 -1.0  1.0  1.0 -1.0
7  1.0  1.0  1.0  1.0

In [5]:
Cuadrado['resultados'] = [45, 100, 45, 65, 75, 60, 80, 96]
Cuadrado

     A    B    C    D  resultados
0 -1.0 -1.0 -1.0 -1.0          45
1  1.0 -1.0 -1.0  1.0         100
2 -1.0  1.0 -1.0  1.0          45
3  1.0  1.0 -1.0 -1.0          65
4 -1.0 -1.0  1.0  1.0          75
5  1.0 -1.0  1.0 -1.0          60
6 -1.0  1.0  1.0 -1.0          80
7  1.0  1.0  1.0  1.0          96

In [6]:
mod = ols('resultados~A+B+C+D', Cuadrado).fit()
anova = sm.stats.anova_lm(mod)
anova

           df  sum_sq  mean_sq         F    PR(>F)
A         1.0   722.0    722.0  1.537806  0.303098
B         1.0     4.5      4.5  0.009585  0.928185
C         1.0   392.0    392.0  0.834931  0.428227
D         1.0   544.5    544.5  1.159744  0.360405
Residual  3.0  1408.5    469.5       NaN       NaN

In [7]:
mod.summary()

/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1604: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             resultados   R-squared:                       0.541
Model:                            OLS   Adj. R-squared:                 -0.070
Method:                 Least Squares   F-statistic:                    0.8855
Date:                Fri, 09 Jul 2021   Prob (F-statistic):              0.563
Time:                        22:56:25   Log-Likelihood:                -32.035
No. Observations:                   8   AIC:                             74.07
Df Residuals:                       3   BIC:                             74.47
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     70.7500      7.661      9.235      0.003      46.370      95.130
A              9.5000      7.661      1.240      0.303     -14.880      33.880
B              0.7500      7.661      0.098      0.928     -23.630      25.130
C              7.0000      7.661      0.914      0.428     -17.380      31.380
D              8.2500      7.661      1.077      0.360     -16.130      32.630
==============================================================================
Omnibus:                        0.169   Durbin-Watson:                   2.972
Prob(Omnibus):                  0.919   Jarque-Bera (JB):                0.349
Skew:                           0.113   Prob(JB):                        0.840
Kurtosis:                       2.002   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [8]:
from scipy.stats import t #importa prueba t-student

In [9]:
valor_t = t.cdf(0.95, 7)
# cdf = cumulative density function , donde el primer argumento es el valor p que se quiere y el segundo
# los grados de libertad <factores-1>
valor_t

0.8131247661972878

Se observa que la influencia de B no es significativa en el análisis del analito

### Peso del efecto de cada factor significativo

In [10]:
mod = ols('resultados~A+C+D+A*C+A*D', Cuadrado).fit()
anova2 = sm.stats.anova_lm(mod)
anova2

           df  sum_sq  mean_sq           F    PR(>F)
A         1.0   722.0   722.00  222.153846  0.004471
C         1.0   392.0   392.00  120.615385  0.008189
D         1.0   544.5   544.50  167.538462  0.005916
A:C       1.0   684.5   684.50  210.615385  0.004714
A:D       1.0   722.0   722.00  222.153846  0.004471
Residual  2.0     6.5     3.25         NaN       NaN

In [11]:
mod.summary()

/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1604: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             resultados   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     188.6
Date:                Fri, 09 Jul 2021   Prob (F-statistic):            0.00528
Time:                        22:56:25   Log-Likelihood:                -10.521
No. Observations:                   8   AIC:                             33.04
Df Residuals:                       2   BIC:                             33.52
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     70.7500      0.637    111.002      0.000      68.008      73.492
A              9.5000      0.637     14.905      0.004       6.758      12.242
C              7.0000      0.637     10.983      0.008       4.258       9.742
D              8.2500      0.637     12.944      0.006       5.508      10.992
A:C           -9.2500      0.637    -14.513      0.005     -11.992      -6.508
A:D            9.5000      0.637     14.905      0.004       6.758      12.242
==============================================================================
Omnibus:                        0.414   Durbin-Watson:                   1.654
Prob(Omnibus):                  0.813   Jarque-Bera (JB):                0.439
Skew:                           0.000   Prob(JB):                        0.803
Kurtosis:                       1.852   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [12]:
prueba_t = t.cdf(0.95, 2) 
prueba_t

0.7788094536697808

Ahora en este caso se puede observar que los factores A, C y D tienen una significancia similar y pueden ser considerados factores principales que afectan el análisis.